import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import ChatScreen from "../../components/ChatScreen";
import Sidebar from "../../components/Sidebar";

const Chat = () => {
  const { data: session, status } = useSession();
  if (status === "unauthenticated") {
    return signIn();
  }

  return (
    <div className="flex">
      <Head>
        <title>WhatsApp 1.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/whatsapp.ico" />
      </Head>
      {session && (
        <>
          <Sidebar />
          <div className="flex-1">
            <ChatScreen />
          </div>
        </>
      )}
    </div>
  );
};

export default Chat;

// export async function gerServerSideProps(context) {}
